- hosts: all
  serial: 1
  gather_facts: no
  tasks:
    - name: Start Kasm Services
      shell: /opt/kasm/bin/start
      register: start_output
      changed_when: '"done" in start_output.stderr'
      become: true
