---
# List of files in the files directory matching the installer, service_images, and workspace images.

- name: Set installer, service images, workspace images, and network plugin file globs
  ansible.builtin.set_fact:
    install_common_installer_glob: "{{ lookup('fileglob', role_path + '/files/kasm_workspaces_*.tar.gz', wantlist=True) +
      lookup('fileglob', role_path + '/files/kasm_release_*.tar.gz', wantlist=True) }}"
    install_common_service_images_glob: "{{ lookup('fileglob', role_path + '/files/kasm_workspaces_service_images*.tar.gz', wantlist=True) +
      lookup('fileglob', role_path + '/files/kasm_release_service_images*.tar.gz', wantlist=True) }}"
    install_common_workspace_images_glob: "{{ lookup('fileglob', role_path + '/files/kasm_workspaces_workspace_images_*.tar.gz', wantlist=True) +
      lookup('fileglob', role_path + '/files/kasm_release_workspace_images_*.tar.gz', wantlist=True) }}"
    install_common_network_plugin_glob: "{{ lookup('fileglob', role_path + '/files/kasmweb_network_plugin_*.tar.gz', wantlist=True) }}"
  delegate_to: localhost

- name: Set installer, service images, workspace images, and network plugin file facts
  ansible.builtin.set_fact:
    # Our installer glob search will also include service_images and workspace_images so we filter them out with difference()
    install_common_installer_file: "{{ install_common_installer_glob | difference(install_common_service_images_glob)
      | difference(install_common_workspace_images_glob) | first | default(None) }}"
    install_common_service_images_file: "{{ install_common_service_images_glob | first | default(None) }}"
    install_common_workspace_images_file: "{{ install_common_workspace_images_glob | first | default(None) }}"
    install_common_network_plugin_file: "{{ install_common_network_plugin_glob | first | default(None) }}"

- name: Assert that Kasm installer exists
  ansible.builtin.assert:
    that:
      - install_common_installer_file is not none
    fail_msg:
      - "Kasm installer not found"
      - "Ensure that kasm_workspaces installer tarfile is in {{ role_path }}/files/"

- name: Unarchive kasm installer
  ansible.builtin.unarchive:
    src: "{{ install_common_installer_file }}"
    dest: "{{ install_common_tempdir.path }}"

- name: Copy service images
  ansible.builtin.copy:
    src: "{{ install_common_service_images_file }}"
    dest: "{{ install_common_tempdir.path }}"
    mode: "0644"
  register: install_common_service_images_copy
  when: install_common_service_images_file is not none

- name: Copy Workspace images
  ansible.builtin.copy:
    src: "{{ install_common_workspace_images_file }}"
    dest: "{{ install_common_tempdir.path }}"
    mode: "0644"
  register: install_common_workspace_images_copy
  when: install_common_workspace_images_file is not none

- name: Copy Network Plugin
  ansible.builtin.copy:
    src: "{{ install_common_network_plugin_file }}"
    dest: "{{ install_common_tempdir.path }}"
    mode: "0644"
  register: install_common_network_plugin_copy
  when: install_common_network_plugin_file is not none
