---
- name: Set default credentials
  ansible.builtin.include_tasks:
    file: default_credentials.yml

- name: Check if Kasm is installed
  ansible.builtin.stat:
    path: /opt/kasm/current
  register: install_common_kasm_path

- name: Set install_common_kasm_installed fact
  ansible.builtin.set_fact:
    install_common_kasm_installed: "{{ install_common_kasm_path.stat.exists }}"

- name: Set web_ip to current host if default_web is false
  ansible.builtin.set_fact:
    install_common_web_host: "{{ hostvars[group_names[0] + '_web_' + inventory_hostname.split('_')[2]].ansible_facts['fqdn'] }}"
    # IP of the host that ansible is being ran against
    install_common_target_host: "{{ ansible_facts['fqdn'] }}"
  when: not (default_web | bool)

- name: Set web_ip to default web host if default_web is true
  ansible.builtin.set_fact:
    install_common_web_host: "{{ hostvars[group_names[0] + '_web_' + default_web | string].ansible_facts['fqdn'] }}"
    # IP of the host that ansible is being ran against
    install_common_target_host: "{{ ansible_facts['fqdn'] }}"
  when: default_web | bool

- name: Set default db host if database_hostname is not set
  ansible.builtin.set_fact:
    install_common_db_host: "{{ hostvars['zone1_db_1'].ansible_facts['fqdn'] }}"
  when: not database_hostname

- name: Set db host to database_hostname if it is set
  ansible.builtin.set_fact:
    install_common_db_host: "{{ database_hostname }}"
  when: database_hostname

- name: Override manager hostname if configured
  ansible.builtin.set_fact:
    install_common_web_host: "{{ manager_hostname }}"
  when: manager_hostname is defined

- name: Check if kasm swapfile exists
  ansible.builtin.stat:
    path: /mnt/kasm.swap
  register: install_common_kasm_swapfile
  when:
    - "'agent' in group_names[1].split('_')"

- name: Calculate new swap size
  ansible.builtin.set_fact:
    # We only want to make a swapfile large enough to make up the difference between
    # the current swapsize and our desired size.
    install_common_new_swap_size: "{{ desired_swap_size | human_to_bytes - (ansible_facts['memory_mb']['swap']['total'] * 1024 * 1024) | int }}"
  when:
    - "'agent' in group_names[1].split('_')"

- name: Run swap tasks
  ansible.builtin.include_tasks:
    file: mkswap.yml
  when:
    - "'agent' in group_names[1].split('_')"
    - install_common_new_swap_size | int > 0
    - not install_common_kasm_swapfile.stat.exists

- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: install_common_tempdir

# Debian 10 doesn't ship with the ca-certificates package installed by default
# installing curl is portable to to ensure that ca-certificates is installed
- name: Ensure we have curl installed
  ansible.builtin.package:
    name: curl
    state: present
  become: true

- name: Copy installer and images to target host
  ansible.builtin.include_tasks:
    file: copy_installer.yml
  when:
    - not install_common_kasm_installed

- name: Add additional zones tasks
  ansible.builtin.include_tasks:
    file: add_zones.yml
  when:
    - not install_common_kasm_installed

- name: Run Kasm db install tasks
  ansible.builtin.include_tasks:
    file: db_install.yml
  when:
    - "'db' in group_names[1].split('_')"
    - not install_common_kasm_installed

- name: Run remote db init tasks
  ansible.builtin.include_tasks:
    file: remote_db_init.yml
  when:
    - init_remote_db
    - database_hostname
    - "'web' in group_names[1].split('_')"
    - not install_common_kasm_installed

- name: Run Kasm web install tasks
  ansible.builtin.include_tasks:
    file: web_install.yml
  when:
    - "'web' in group_names[1].split('_')"
    - not install_common_kasm_installed

- name: Run Kasm agent install tasks
  ansible.builtin.include_tasks:
    file: agent_install.yml
  when:
    - "'agent' in group_names[1].split('_')"
    - not install_common_kasm_installed

- name: Run Kasm guac install tasks
  ansible.builtin.include_tasks:
    file: guac_install.yml
  when:
    - "'guac' in group_names[1].split('_')"
    - not install_common_kasm_installed

- name: Run Kasm proxy install tasks
  ansible.builtin.include_tasks:
    file: proxy_install.yml
  when:
    - "'proxy' in group_names[1].split('_')"
    - not install_common_kasm_installed

- name: Enable the docker service to run at boot
  ansible.builtin.service:
    name: docker
    enabled: true
  become: true
  when: start_docker_on_boot

- name: Delete temporary directory
  ansible.builtin.file:
    path: "{{ install_common_tempdir.path }}"
    state: absent
  become: true

- name: Print credentials
  ansible.builtin.debug:
    msg:
      - "Database Password: {{ database_password }}"
      - "Manager Token: {{ manager_token }}"
      - "Registration Token: {{ registration_token }}"
      - "user@kasm.local password: {{ user_password }}"
      - "admin@kasm.local password: {{ admin_password }}"
  run_once: true

- name: Write credentials to inventory
  run_once: true
  delegate_to: localhost
  ansible.builtin.template:
    src: "{{ inventory_file }}"
    dest: "{{ inventory_file }}"

- name: Set credentials to active
  run_once: true
  delegate_to: localhost
  ansible.builtin.replace:
    dest: "{{ inventory_file }}"
    regexp: "{{ item.from }}"
    replace: "{{ item.to }}"
  loop:
    - { from: "#user_password", to: "user_password" }
    - { from: "#admin_password", to: "admin_password" }
    - { from: "#database_password", to: "database_password" }
    - { from: "#manager_token", to: "manager_token" }
    - { from: "#registration_token", to: "registration_token" }

- name: Turn off remote db init
  run_once: true
  delegate_to: localhost
  ansible.builtin.replace:
    dest: "{{ inventory_file }}"
    regexp: "init_remote_db: true"
    replace: "init_remote_db: false"
  when:
    - init_remote_db
    - database_hostname
