---
- name: Check connection from web to postgres on db server
  ansible.builtin.wait_for:
    port: 5432
    host: "{{ install_common_db_host }}"
    timeout: 60

- name: Install web role
  ansible.builtin.command: >
    bash {{ install_common_tempdir.path }}/kasm_release/install.sh
      --role app
      --accept-eula
      --proxy-port {{ proxy_port }}
      --db-hostname {{ install_common_db_host }}
      --db-password {{ database_password }}
      --api-hostname {{ install_common_target_host }}
      --database-user {{ database_user }}
      --database-name {{ database_name }}
      --db-port {{ database_port }}
      --server-zone {{ group_names[0] }}
      {{ '--no-db-ssl ' if not database_ssl }}
      {{ '--offline-service ' ~ install_common_service_images_copy.dest if install_common_service_images_file }}
      {{ '--offline-workspaces ' ~ install_common_workspace_images_copy.dest if install_common_workspace_images_file }}
  register: install_output
  become: true
  retries: 20
  delay: 10
  until: install_output is success or ('Failed to lock apt for exclusive operation' not in install_output.stderr and '/var/lib/dpkg/lock' not in
    install_output.stderr)
